### ISSUE TITLE
wrong architecture and subfolder for examples

### ISSUE THREAD

**Issue by reaper7** [gmag11/NtpClient#1]
please change:
library.properties->architectures=ESP8266 to architectures=esp8266

```
WARNING: library NtpClient claims to run on [ESP8266] architecture(s) and may be incompatible with your current board which runs on [esp8266] architecture(s).
```

<br><br>
and move examples folder from src subdir to top of repository

**Comment by gmag11** [comment]
Changed. I hope it is ok now

**Comment by reaper7** [comment]
almost :)
example ino file name(case sensitive):
from
N**tp**Client.ino
to
N**TP**Client.ino
(must be the same as folder name)

**Comment by gmag11** [comment]
Done! Thank you very much. This is my first library.

**Comment by reaper7** [comment]
now is ok!

maybe first but good :)
tnx too!
