### ISSUE TITLE
Project has no license

### ISSUE THREAD

**Issue by simonlbn** [gmag11/NtpClient#10]
Hi,

Could you please add an explicit software license to the project (at least I can't find any)? Personally I prefer 2 clause BSD, but LGPL is also common in the Arduino world as far as I have seen.

Your project looks really interesting for my use, but as it has no license I cannot use it at this time.

**Comment by gmag11** [comment]
You are right! I was too lazy to include it. Just added to master and develop branches. Please close this issue if you agree solution

**Comment by simonlbn** [comment]
Looks good, thanks!
