### ISSUE TITLE
Problem in ESP32

### ISSUE THREAD

**Issue by hznupeter** [gmag11/NtpClient#100]
i use the esp32 example (https://github.com/gmag11/NtpClient/blob/master/examples/NTPClientESP32/NTPClientESP32.ino)

I change the wifi info, but it can't work well.
the OUTPUT as below:
`[WiFi-event] event: 4
Connected to Xiaomi_0432. Asking for IP address.
[WiFi-event] event: 7
Got IP: 192.168.31.193
Connected: yes
NTP request Sent
assertion "pbuf_free: p->ref > 0" failed: file "/Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/lwip/lwip/src/core/pbuf.c", line 765, function: pbuf_free
abort() was called at PC 0x400d8cdf on core 1

Backtrace: 0x4008c818:0x3ffc8cc0 0x4008ca49:0x3ffc8ce0 0x400d8cdf:0x3ffc8d00 0x400f38ff:0x3ffc8d30 0x400d3c1f:0x3ffc8d50 0x400d3c6f:0x3ffc8de0 0x400887b5:0x3ffc8e10

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1100
load:0x40078000,len:9232
load:0x40080400,len:6400
entry 0x400806a8

[WiFi-event] event: 4
Connected to Xiaomi_0432. Asking for IP address.
[WiFi-event] event: 7
Got IP: 192.168.31.193
Connected: yes
NTP request Sent
assertion "pbuf_free: p->ref > 0" failed: file "/Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/lwip/lwip/src/core/pbuf.c", line 765, function: pbuf_free
abort() was called at PC 0x400d8cdf on core 1
`

**Comment by ghost** [comment]
I have exactly the same issue on ESP32. It looks like a duplicate of issue#99

**Comment by hznupeter** [comment]
@fra-iesus thk, I fix it.you can Pull a request to @gmag11
