### ISSUE TITLE
ESPAsyncUDP dependency on esp32

### ISSUE THREAD

**Issue by Clickau** [gmag11/NtpClient#106]
Even though in library.json, the espasyncudp dependency specifies the platform as "espressif8266", when compiling for the esp32, it lists it as a dependency and includes it (which results in an error because it can't find user_interface.h). If the library espasyncudp is not installed, it doesn't even list it as a dependency and works fine. Might be something from PlatformIO?

**Comment by telliottosceola** [comment]
Seeing the same thing.  Uninstalling ESPAsyncUDP fixes the problem.  However then I have other compilation errors which just came up the other day.

**Comment by steveb999** [comment]
Same for me using vscode and platformio

**Comment by gmag11** [comment]
Check new library version on https://github.com/gmag11/ESPNtpClient. It does not use AsyncUDP but internal LWIP funcions. Therefore it does not have any external dependency.

It is published in Platformio registry
