### ISSUE TITLE
daylight savings time not accounted for in getTimeZone()

### ISSUE THREAD

**Issue by sgorpi** [gmag11/NtpClient#11]
Hi,

Not sure what the desired behavior would be, but the daylight saving time (DST) is not accounted for when you do getTimeZone(). That needs extra logic on the user side to account for DST if that option is enabled. Not sure which is more correct to provide though ;)

Cheers

**Comment by sgorpi** [comment]
In addition: the user then has to write his own bool summertime(int year, byte month, byte day, byte hour, byte tzHours);
So maybe it's better to account for it in getTimeZone().

Cheers

**Comment by gmag11** [comment]
I'll test it. I do not understand what you mean about summertime function. There is a function already defined inside class and used to find if a date is summer time or not. DST must be activated in `begin()` call. It is deactivated by default.

**Comment by sgorpi** [comment]
So, what I want to achieve is this: Send an email with the correct Date: header, which looks like "Date: Sep, 21 Sep 2016 21:40:21 +0100"
The +0100 is the indication of the timezone. Due to it currently being summertime (and me enabling the summertime correction), this should read +0200 in my region, but it doesn't. So, while the actual time is correctly adjusted for summertime, the getTimeZone is not. 

In order for the user of the library to correct for this, he needs to know not only if DST correction is enabled, but also if it currently is the summertime period. You have a nice function for that in the library, but it is private, and thus not usable for an end user. 
Therefore, I think it is best to return the summertime-adjusted timezone in getTimeZone() if DST is enabled. (For backwards compatibility, you could add a flag, e.g., getTimeZone(bool adjustedForDST=false))

Cheers

**Comment by gmag11** [comment]
I think I've got what you mean.

I've added two public methods to develop branch.

`boolean isSummerTime()` returns true if current time is inside summertime period and false if it is winter time. If NTP is configured to not have DST enabled it always return false.

`boolean isSummerTimePeriod(time_t moment)` returns true if given time is inside summertime period.

I've checked that time zone is applied and can be changed with inmediate effect. Could you share your NTP initialization code?

**Comment by gmag11** [comment]
As there is no answer after one month and I think it is solved I close the issue.
