### ISSUE TITLE
Wrong time in NTPClientAvr example

### ISSUE THREAD

**Issue by Shumatic** [gmag11/NtpClient#110]
Could you explain what function on 8266 you refer to here, i cant find any NTP functions  in Arduino IDE or ? - could you point me to it :-)
>With new improvements in sdk both for esp32 and esp8266, this library has become less usefull. Using internal functions of IDF or NonOS (esp8266) have several advantages and it is mandatory for certain scenarios, like using HTTPS with certificate<

another issue....
I have tried the NTPClientAvr example on a Arduino Mega 2560, and it sync to a wrong time 07:26:50 07/02/2036. Winter Time. unix: 2085982010 - (should be 31-03-2020 16:10). the unix time where taken with now(). it also seems really unstable.sometimes it doesn't sync and some time it stops syncing, 
Only change from example is ethernet setup and NTP.begin("dk.pool.ntp.org", 1, true, 0);

Thanks in advance

**Comment by gmag11** [comment]
For ESP32 and ESP8266 you can use my new developed library https://github.com/gmag11/ESPNtpClient. Its use is very similar to this one but adds much higher sync accuracy and does not use external libraries.

Regarding AVR, I am not able to test neither AVR or MKR code as I do not own any board like that anymore. That's one of the reasons to stop developing this and move my effort to the new lib.

**Comment by gmag11** [comment]
Regarding simple NTP configuration on ESP8266 and ESP32 you can check this: https://github.com/gmag11/NtpClient/issues/60#issuecomment-724473640
