### ISSUE TITLE
Please... is there any way to get the day of the week ?  (Sunday, Monday etc.)  Thanks  

### ISSUE THREAD

**Issue by pinozgit** [gmag11/NtpClient#113]

**Comment by furynick** [comment]
You can use TimeLib.h :
```
uint8_t aa, mo, dd, wd, hh, mm, ss;
time_t t = now();
aa = year(t);
mo = month(t);
dd = day(t);
wd = weekday(t);
hh = hour(t);
mm = minute(t);
ss = second(t);
```

**Comment by gmag11** [comment]
@pinozgit If you are using ESP32 or ESP8266 I recommend you to go for my other library https://github.com/gmag11/ESPNtpClient. Its use is similar to this one but can get higher sync precission and you can use standard time library to get time in different formats: https://ftp.gnu.org/old-gnu/Manuals/glibc-2.2.3/html_chapter/libc_21.html
