### ISSUE TITLE
 Getting error: "reference to 'byte' is ambiguous" with Arduino IDE1.8.15

### ISSUE THREAD

**Issue by bill-orange** [gmag11/NtpClient#114]
Since updating to Arduino IDE1.8.15, I am getting the compiler error:'

> error: reference to 'byte' is ambiguous

`bool summertime (int year, byte month, byte day, byte hour, byte weekday, byte tzHours);`

when using this library.  It appears that there is some change in the use of the type byte.

I re-tested with NTPClientBasic and confirmed the problem.  

Is there a work-around? 

**EDIT:

I discovered that the problem was not with the IDE but was with the compiler/board manager.  I reverted to esp8266 ver 2.7.4 from 3.0.0 and all was well.

Hardly a permanent solution.  I am not sure if this is a bug or a feature.

**Comment by stef-ladefense** [comment]
I have the same concern
I have not yet found where it comes from
i have errors from arduino.h regarding byte

**Comment by bill-orange** [comment]
I looks like the developers broke a lot of things with 3.0.0  although I don't see `byte` on the list.

https://github.com/esp8266/Arduino/releases

**Comment by stef-ladefense** [comment]
you can test this : https://github.com/stef-ladefense/NtpClient/commit/ed22ce90048cf9d06c57c34208f2b5328a76c6d4

and have change in C:\Users\xxxxx\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.0\cores\esp8266\Arduino.h
line 247
uint16_t makeWord(byte h, byte l);
to
uint16_t makeWord(uint8_t h, uint8_t l);

**Comment by stef-ladefense** [comment]
> and have change in C:\Users\xxxxx\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.0\cores\esp8266\Arduino.h
> line 247
> uint16_t makeWord(byte h, byte l);
> to
> uint16_t makeWord(uint8_t h, uint8_t l);

see https://github.com/esp8266/Arduino/issues/8089

**Comment by bill-orange** [comment]
Yes, that fork works fine in both version 2.7.4 and version 3.0.0  even without changing Arduino.h.  

ESP8266Ping.h is also broken.  I think it will need the change to Arduino.h to make it work plus getting rid of byte,

**Comment by stef-ladefense** [comment]
indeed as I note in the post for arduino.h, I use in my code word (h, l) and necessarily I corrected all the errors to compile my code, which included both NtpClient and arduino.h , moreover this is not the only core 3.0.0 file impacted with 'bytes', it will be necessary to learn how to replace by uint8_t

I'm glad it can help

**Comment by bill-orange** [comment]
@stef-ladefense  @gmag11 

Thanks for the help.  I think we can close this issue even though this is likely to be an ongoing problem.

**Comment by gmag11** [comment]
Use of `byte` type was inherited from first tests when I started developing an NTP library. It makes sense to use a standard type like `uint8_t`

**Comment by stef-ladefense** [comment]
I'm not criticizing, I also have some 'byte' leftovers in my sources, and with the new changes we'll have to be more rigorous and that's a good thing

**Comment by gmag11** [comment]
Fixed in https://github.com/gmag11/NtpClient/commit/9624225829f93edcad319adcbba054b1081532bf

**Comment by stef-ladefense** [comment]
merci
