### ISSUE TITLE
Hi, I know this is an old thread, but it annoys me.... And maybe it does not relate to you code, but any help would be appreciated.

### ISSUE THREAD

**Issue by Shumatic** [gmag11/NtpClient#118]
Hi, I know this is an old thread, but it annoys me.... And maybe it does not relate to you code, but any help would be appreciated.
I found out that I get the same error if i only included  "using namespace std; , that is inside your" <NtpClientLib.h> 

I can't figure out why, the only connection with ESP8266mDNS is, they also use std. but none of it relate to MAP 

This is the code that throws the err
"reference to 'map' is ambiguous"

```
using namespace std;
#include <ESP8266mDNS.h>
void setup() {
// put your setup code here, to run once:
int x = map(55, 1000, 3, 5, 800);
}
void loop() {
}
```

_Originally posted by @Shumatic in https://github.com/gmag11/NtpClient/issues/108#issuecomment-1214834408_

**Comment by gmag11** [comment]
Hi
This question is not related to this repository. Please use any Arduino forum. Sorry
