### ISSUE TITLE
compile error?

### ISSUE THREAD

**Issue by rspaargaren** [gmag11/NtpClient#12]
If I try to compile the example as listed on the readme page I get the following compile error?

Arduino: 1.6.5 (Windows 8.1), Board:"NodeMCU 1.0 (ESP-12E Module), 80 MHz, Serial, 115200, 4M (3M SPIFFS)"

Build-opties gewijzigd, alles wordt opnieuw gebuild

In file included from C:\Users\Richard\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.0.0/tools/sdk/include/os_type.h:10:0,
                 from C:\Users\Richard\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.0.0/tools/sdk/include/user_interface.h:9,
                 from C:\Users\Richard\Documents\Arduino\libraries\NtpClient-master\src\NtpClientLib.h:45,
                 from C:\Users\Richard\Documents\Arduino\libraries\NtpClient-master\src\AvrNTPClient.cpp:35:
C:\Users\Richard\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.0.0/tools/sdk/include/ets_sys.h:148:20: error: 'size_t' was not declared in this scope
 void _pvPortMalloc(size_t xWantedSize) **attribute**((malloc, alloc_size(1)));
                    ^
C:\Users\Richard\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.0.0/tools/sdk/include/ets_sys.h:148:77: warning: attributes after parenthesized initializer ignored [-Wattributes]
 void *pvPortMalloc(size_t xWantedSize) **attribute**((malloc, alloc_size(1)));
                                                                             ^
C:\Users\Richard\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.0.0/tools/sdk/include/ets_sys.h:149:32: error: 'size_t' has not been declared
 void *pvPortRealloc(void_ ptr, size_t xWantedSize) **attribute**((alloc_size(2)));
                                ^
C:\Users\Richard\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.0.0/tools/sdk/include/ets_sys.h:151:19: error: 'size_t' was not declared in this scope
 void *vPortMalloc(size_t xWantedSize) **attribute**((malloc, alloc_size(1)));
                   ^
C:\Users\Richard\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.0.0/tools/sdk/include/ets_sys.h:151:76: warning: attributes after parenthesized initializer ignored [-Wattributes]
 void *vPortMalloc(size_t xWantedSize) **attribute**((malloc, alloc_size(1)));
                                                                            ^
C:\Users\Richard\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.0.0/tools/sdk/include/ets_sys.h:153:47: error: 'size_t' has not been declared
 void *ets_memcpy(void *dest, const void *src, size_t n);
                                               ^
C:\Users\Richard\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.0.0/tools/sdk/include/ets_sys.h:154:34: error: 'size_t' has not been declared
 void *ets_memset(void *s, int c, size_t n);
                                  ^
C:\Users\Richard\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.0.0/tools/sdk/include/ets_sys.h:163:48: error: 'size_t' has not been declared
 char *ets_strncpy(char *dest, const char *src, size_t n);
                                                ^
C:\Users\Richard\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.0.0/tools/sdk/include/ets_sys.h:166:28: error: 'size_t' has not been declared
 int os_snprintf(char *str, size_t size, const char *format, ...) **attribute** ((format (printf, 3, 4)));
                            ^
C:\Users\Richard\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.0.0/tools/sdk/include/ets_sys.h:175:29: error: 'size_t' has not been declared
 int ets_vsnprintf(char \* s, size_t n, const char \* format, va_list arg)  **attribute** ((format (printf, 3, 0)));
                             ^
Multiple libraries were found for "TimeLib.h"
 Used: C:\Users\Richard\Documents\Arduino\libraries\Time-master
 Not used: C:\Users\Richard\Documents\Arduino\libraries\Time

Fout bij compileren.

**Comment by gmag11** [comment]
I see that you have Time library in two locations. This can be first problem.
Compiler complaints about size_t definition, that is not in my code but on Arduino esp8266 environment. Maybe you have an outdated esp8266 framework, what version have you installed? I've tested with last stable build 2.3.0
