### ISSUE TITLE
WiFi.onEvent is deprecated

### ISSUE THREAD

**Issue by stelgenhof** [gmag11/NtpClient#15]
First, thanks for the wonderful library! In the ESP8266 example, the follow part is using the WiFi.onEvent handler. 
```
WiFi.onEvent([](WiFiEvent_t e) {
   Serial.printf("Event wifi -----> %d\n", e);
});
```
This handler has been deprecated (See ESP8266WiFiGeneric.h line 54).

Cheers! Sacha

**Comment by gmag11** [comment]
Thank you for your interest. 
I used that method to test event before processing them in next two lines. It is not significant to show library use but you are right. As it is deprecated and can be removed from ESP8266WiFi library I'll remove to avoid future compilation errors.
