### ISSUE TITLE
onNTPSyncEvent() is called before system time is updated.

### ISSUE THREAD

**Issue by 1n5aN1aC** [gmag11/NtpClient#17]
As title.  when a NTP sync occurs, onNTPSyncEvent() is called before it finishes updating the 'system' time.  This can cause extreme confusion to people who expect to be able to use now() and get the updated value within it.

I confirmed this while playing with an RTC, and setting the RTC on NTPsync wasn't working.  Then on a whim, I changed the interval to 30 seconds, and lo and behold, on second sync it worked!

Note that I later found you can use getLastNTPSync() inside the event, so you can close & ignore this if you would like, it's just misleading for new users.

**Comment by gmag11** [comment]
Hi. You are right. This is due I call it in the function that TimeLib uses to sync time. To get desired behaviour TimeLib could implement and onSyncEvent method, but I prefer not to modify that library.
A workaround can be programmed in example code: having a flag that is changed by onSync handler function. So an if statement that checks that flag can do the main job inside main loop.

I will modify ESP8266 example to see if it works. What do you think, @1n5aN1aC ?.

**Comment by 1n5aN1aC** [comment]
Sorry for not getting back to you earlier.

This problem isn't really a problem for me, as I have just started using getLastNTPSync() instead of now() inside the event, which works fine for my purposes.

This ticket is more of informing you of it, because it is non-intuitive, so changing how it works would make it easier for new people using your library.  But if you do not want to changer that, closing the issue would also be fine.

**Comment by gmag11** [comment]
The problem is that forking Time Library may be confusing too. I think having my own version of TimeLib gives not much benefit to overall behaviour.
Thanks for your interest.

**Comment by 1n5aN1aC** [comment]
Yeah- forking TimeLib would not be the best.

I was thinking you could probably do it via a hack by forcing time to be synced completely before sending the call back to the user, but that could be messy and not the best perhaps as well.

Anyways, thanks for your comments!

**Comment by 1n5aN1aC** [comment]
Question-

Does https://github.com/gmag11/NtpClient/commit/60e3d89de44e89543b5d252ce488b41489bd7fb4 'solve' this 'issue'?

**Comment by gmag11** [comment]
Actually not. Event should be triggered by time library. But, as I am not its author i cannot control what it does. I could request a modification, but the way it is now is ok, for me.

Using a flag like example does may be a workaround, but not enough for all projects. In that case, time library should be improved.

**Comment by 1n5aN1aC** [comment]
Alright, thanks!
