### ISSUE TITLE
Trigger time synchroniation manually 

### ISSUE THREAD

**Issue by 7h30n3** [gmag11/NtpClient#19]
Hey,

I'm working on sketch, where I use ModemSleep. I just wake up the ESP irregularly to send new data to a server, if a value of a sensor changed, so there are now certain intervals.

As mentioned in the title, is there a (recommended) way to manually trigger a time synchronisation?

**Comment by gmag11** [comment]
Anytime `begin()`is called, NTP synchronization starts periodically. First a short period is used until it get first successful sync, then a longer period is configured.
If you call `getTime()` anytime, a NTP sync procedure is started, but it is not stored. You can use `setTime(getTime());` to store NTP time on local time.

**Comment by 7h30n3** [comment]
Thanks, that solved my issue.
