### ISSUE TITLE
getTimeDateString() wrong behaviour

### ISSUE THREAD

**Issue by de666** [gmag11/NtpClient#21]
`getTimeDateString()` should print the datetime string even if the time is set but it needs syncronization.
Now it prints "Time not set".

inspecting the code I think it should be simply:
`
String NTPClient::getTimeDateString() {
	return getTimeDateString(now());
}
`

**Comment by gmag11** [comment]
This behavior happens only before first sync, when we know that time is not valid. Can you tell me the use case where you need this?

**Comment by de666** [comment]
It happens also if the time needs sync and there is temporarely no internet connection available and this is the use case.

I mean:

- Internet connection available
- Time sync
- Internet connection not available
- Time need sync (but sync is not possible) => time set but not sync
- Print datetime string => "Time not set" (wrong, time is set but only need sync)
- Internet connection available
- Time sync
- Print datetime string => OK

Anyway looking at the code I don't understand why `getDateStr()` and `getTimeStr()` should have a different behaviour from `getTimeDateString()`.

**Comment by gmag11** [comment]
@de666 I'll have a look. Thanks

**Comment by gmag11** [comment]
@de666 I've updated [develop](https://github.com/gmag11/NtpClient/tree/develop) branch. Please test it.

**Comment by gmag11** [comment]
I've tested myself and works. I move it to master branch
