### ISSUE TITLE
crash on acquire  time on async lib 

### ISSUE THREAD

**Issue by mkeyno** [gmag11/NtpClient#22]
thanks Martin for lib but sometime acquire time from server make my async sketch crash ? have you try use your lib with menodev async lib ?

**Comment by RudyFiero** [comment]
He uses it in FSBrowserNG https://github.com/gmag11/FSBrowserNG and that also uses me-no-dev async libraries.

I have only tested it a few times.

**Comment by mkeyno** [comment]
me also test this sketch before but ```void AsyncFSWebServer::send_NTP_configuration_html(AsyncWebServerRequest *request)``` is not the handler for ntc server respond , it is just update the time setting parameters  on  user request then ``setTime(NTP.getTime());`` handle the rest , what I  interested is async handler for server respond like google time or other website

**Comment by gmag11** [comment]
@mkeyno Sorry, I do not understand what you actually need.

There is a callback function that is called just before time is synced. I do not know if it fits your need.

**Comment by gmag11** [comment]
I close this issue. You can reopen it if necessary.
