### ISSUE TITLE
onNTPSyncEvent not called

### ISSUE THREAD

**Issue by MarcFinns** [gmag11/NtpClient#23]
hello, 
I would have a question: I dont see the onNTPSyncEvent called, unless  i call other NTP APIs (e.g. getTimeDateString). Is this the expected behavior?
thanks for your time!

**Comment by gmag11** [comment]
Event triggering was revised in last commits. It should work.

It should be called in case of error or just one line before time is actually synced. Have you tried library example?

**Comment by MarcFinns** [comment]
Is it supposed to be called no matter what, or only if I explicitly call any other NTP API?

**Comment by gmag11** [comment]
It is called inside getTime method. You can call it manually but it is automatically called from time to time according to configured sync period. It is done in TimeLib library.
