### ISSUE TITLE
Time zone change

### ISSUE THREAD

**Issue by MarcFinns** [gmag11/NtpClient#24]
Hello,
In my project I use Google Geolocation and Timezone API. 
At the beginning I set the NTP library with UTC time zone and no daylight savings.
Once I acquire the timezone via Google I call NTP.setDayLight() and NTP.setTimeZone().
My expectation would be that the time is adjusted accordingly but apparently it is not.
Is it a bug or a misunderstanding on the expected behavior?
thank you again!

**Comment by gmag11** [comment]
Currently, time is recalculated in next iteration. You're right. It makes more sense to trigger a time resync inmediately. I'll make a test branch and will ask you to test.

**Comment by MarcFinns** [comment]
Happy to do so. Let me know when ready..

**Comment by gmag11** [comment]
Please test develop branch

**Comment by MarcFinns** [comment]
Will try to spare some time this evening... thanks

**Comment by MarcFinns** [comment]
Hi there, i just found some time to test the dev branch.
It seems that when i call setTimeZone the time is invalidated and becomes 00:00 until the next sync. why dont you just increment / decrement the current time with the offset provided?

**Comment by gmag11** [comment]
I'm using internal sntp esp8266 SDK calls instead of own code. This limits what I can do with it. I'm working on integrating same code for ESP8266 and other platforms (Arduino) to get control on these specific cases.

After setting time zone I try a new sync. Indeed, for esp8266 I do not use a variable to store time zone. Everything is inside esp8266 SDK.

**Comment by gmag11** [comment]
@MarcFinns I've improved behaviour when changing time zone. Please test newest release

**Comment by MarcFinns** [comment]
That's well appreciated, I had to put in place a hack to work around the current behaviour. I am out of the country but I will test it asap. What is the new intended behaviour? Thanks again

**Comment by gmag11** [comment]
Before, when ntp failed, getTime returned 0 and time was reset. 1st sync always fails (I do not know why) and sync is triggered when changing time zone. So, if time zone is changed and there is no connection, time is reset to 0.

Now, time is kept with or without internet. If get time fails it now returns current time.

**Comment by MarcFinns** [comment]
Sounds better. Is time incremented when no connection?

**Comment by gmag11** [comment]
Yes. I keep track of configured offset. If it is changed the difference is calculated to modify time accordingly.
