### ISSUE TITLE
Question: ESP32 support?

### ISSUE THREAD

**Issue by MarcFinns** [gmag11/NtpClient#26]
Hello German, I was wondering whether you are considering an ESP32 port of the library.
My project has grown too large for the ESP8266 and i am considering switching boards... but a few libs dont compile / have hardware dependencies...
Would you consider it a difficult thing? please let me know. 
Again, thank you for your time.

**Comment by gmag11** [comment]
I do not have an ESP32 to test. Most probably code has to be reworked to be compatible with it.
