### ISSUE TITLE
return epoch

### ISSUE THREAD

**Issue by apreb** [gmag11/NtpClient#27]
Hi,

Great library, thanks for your great work.

The library is missing a simple epoch time to use for my IoT updates.
i've added this function to your library, not sure if it needs improvement to handle trouble with NTP servers.

time_t NTPClient::getDateEpoch()
{
	return now();
}

If you find it reasonable could you add this or other function you find appropriate to get epoch time?

Thanks.

**Comment by gmag11** [comment]
Hi @apreb 

NTPClientLib does not manage time, it only updates it after getting information from NTP server. TimeLib is the one that does that and you have already discovered the funcion that does that: it is `now()`.

**Comment by apreb** [comment]
Thank you for the explanation
