### ISSUE TITLE
Bug? Sync does not kick in unless I wait for it

### ISSUE THREAD

**Issue by MarcFinns** [gmag11/NtpClient#28]
Hello German,

I noticed a strange behavior, that I can reproduce with the code below, typically execute in the setup() method.
Basically, I setup NTP with code inspired by your examples. If I wait for the first sync then it behaves perfectly. If I comment out the while loop, then synch never takes place.
Am I doing something wrong or is it a bug?
Thanks!

  // NTP start
  NTP.onNTPSyncEvent([](NTPSyncEvent_t error)
  {
    if (error)
    {
      Serial.println("NTP sync ERROR");
      if (error == noResponse)
        syslog.log(LOG_ERR, F("NTP server not reachable"));
      else if (error == invalidAddress)
        syslog.log(LOG_ERR, F("Invalid NTP server address"));
    }
    else
    {
      Serial.println("NTP GOT TIME" + NTP.getTimeDateString(NTP.getLastNTPSync()));
      syslog.log(LOG_INFO, "Got NTP time - " + NTP.getTimeDateString(NTP.getLastNTPSync()));
    }
  });

  e1 = WiFi.onStationModeGotIP(onSTAGotIP);
  e2 = WiFi.onStationModeDisconnected(onSTADisconnected);

  NTP.begin(FPSTR(ntpServerName), 0, false);
  NTP.setInterval(5, 600);

  // without this delay, sync never kicks in
  while (NTP.getLastNTPSync() == 0)
  {
    //#ifdef DEBUG_LOG
    Serial.print(".");
    //#endif
    delay(500);
    NTP.getTimeDateString();
  }
  Serial.println(NTP.getTimeDateString());

**Comment by gmag11** [comment]
Hi @MarcFinns 
May you indicate what part belongs to `setup()` and `loop()` so that I can try to reproduce it?

**Comment by MarcFinns** [comment]
oh sorry..

1)***** IN A FUNCTION CALLED FROM SETUP:
// NTP start
 NTP.onNTPSyncEvent([](NTPSyncEvent_t error)
 {
 if (error)
 {
 Serial.println("NTP sync ERROR");
 if (error == noResponse)
 syslog.log(LOG_ERR, F("NTP server not reachable"));
 else if (error == invalidAddress)
 syslog.log(LOG_ERR, F("Invalid NTP server address"));
 }
 else
 {
 Serial.println("NTP GOT TIME" + NTP.getTimeDateString(NTP.getLastNTPSync()));
 syslog.log(LOG_INFO, "Got NTP time - " + NTP.getTimeDateString(NTP.getLastNTPSync()));
 }
 });

e1 = WiFi.onStationModeGotIP(onSTAGotIP);
 e2 = WiFi.onStationModeDisconnected(onSTADisconnected);

2)***** IN A FUNCTION CALLED FROM LOOP (i.e. i do it after I retrieved the correct location and timezone, which happens periodically)
NTP.begin(FPSTR(ntpServerName), 0, false);
 NTP.setInterval(5, 600);

// without this delay, sync never kicks in
 while (NTP.getLastNTPSync() == 0)
 {
 //#ifdef DEBUG_LOG
 Serial.print(".");
 //#endif
 delay(500);
 NTP.getTimeDateString();
 }
 Serial.println(NTP.getTimeDateString());

**Comment by gmag11** [comment]
NTP.begin() should only be called once, it starts the process to periodically get time from NTP. If begin is not called time is never sync'ed.

Does this answer your question?

Regards
