### ISSUE TITLE
timelib millisecond support

### ISSUE THREAD

**Issue by countrysideboy** [gmag11/NtpClient#31]
Here is the solution:
http://forum.arduino.cc/index.php?topic=236425.0

Wait for the network delay compensation function...

**Comment by gmag11** [comment]
Thank you!

As I currently use internal ESP8266 SDK sntp function calls I'm stick to 1 second resolution. I'm trying to implement NTP protocol in a separate function so I can control what it does.

I will not be soon as my real world job get most of my time.

**Comment by gmag11** [comment]
I've rewritten the lib to have same code for all platforms, getting rid of internal espressif NTP calls from SDK. This will allow to improve sync algorithm. It is on https://github.com/gmag11/NtpClient/tree/pre2.5.0.

Next step (with no ETA yet :( ) will be implementing complete NTP calculation to get millisecond precision.

**Comment by gmag11** [comment]
I've tried to modify TimeLib, but there are more features that I'd like to try in a different way. Probably I'll try to develop a new TimeLib with millisecond precission. But it will not happen soon, sorry.

**Comment by rayvt** [comment]
I wrote code to get millisecond precision.  It's not very hard, but I don't think it is worth it.  The native millis() gives you accurate timing regardless of using ntptime or not.  The unix time_t is seconds, and there is not really any need to get finer granularity than that.  Setting the time-of-day clock to the nearest second is good enough.

**Comment by gmag11** [comment]
I was trying to have a way to synchronize several boards to do coordinated tasks without communication between them.
This can be useful to synchronize LED animations with different boards.
But as timelib is limited to second resolution the only way, besides creating a new timelib implementation, is to delay time syncronization to the next exact second.

**Comment by gmag11** [comment]
This won't be implemented in the short term. I close the issue
