### ISSUE TITLE
Usage without a call in loop() possible?

### ISSUE THREAD

**Issue by an-erd** [gmag11/NtpClient#32]
Hi Germain, 

I'm using the version 2.0.5 with an esp8266 board.
When I use exactly the example "NTPClientESP8266", it works fine. But when the ntp relevant  calls in loop() are commented out, I only get the following lines in the serial console:
`Got IP: 192.168.2.150
Time Sync error: NTP server not reachable
`
That's is, there's no additional activity or calls.

Loop() reads like this, all other code is exactly as in the example:

`void loop()
{
	static int i = 0;
	static int last = 0;

	if (syncEventTriggered) {
		processSyncEvent(ntpEvent);
		syncEventTriggered = false;
  }
	delay(0);
}`

My understanding was, that the library performs the necessary calls in the background to update the time or at least get to a status where the time has been successfully retrieved.

Maybe I just misunderstood the usage of the library. Can you please clearify or give me a link to some relevant documentation?

Thanks
Andreas

**Comment by gmag11** [comment]
Yes, everything is managed inside library. To keep time in track you only need to call begin() function inside setup()
