### ISSUE TITLE
Separated parts of time and date

### ISSUE THREAD

**Issue by Azuzula** [gmag11/NtpClient#33]
Hello @gmag11,
because I need each part of date and time separate, then I modify your source code.
Now I can call each part of time and date individualy with no parsing strings.

I don't understand to all of the code, but it work for me.
Do you mind put this into your library officially?

This code call each part of date and time individualy:
```NTP.getHours();
NTP.getMinutes();
NTP.getSeconds();
NTP.getDay();
NTP.getMonth();
NTP.getYear();
```

I added this lines to the NtpClientLib.h:
```String getSeconds();
String getSeconds(time_t moment);
String getMinutes();
String getMinutes(time_t moment);
String getHours();
String getHours(time_t moment);
String getDay();
String getDay(time_t moment);
String getMonth();
String getMonth(time_t moment);
String getYear();
String getYear(time_t moment);
```

And this to the AvrNTPClient.cpp and ESPNTPClient.cpp:
```String NTPClient::getSeconds(time_t moment) {
	if ((timeStatus() != timeNotSet) || (moment != 0)) {
		return printDigits(second(moment));
	}
	else return F("Seconds not set");
}
String NTPClient::getSeconds() {
	return getSeconds(now());
}

String NTPClient::getMinutes(time_t moment) {
	if ((timeStatus() != timeNotSet) || (moment != 0)) {
		return printDigits(minute(moment));
	}
	else return F("Minutes not set");
}
String NTPClient::getMinutes() {
	return getMinutes(now());
}

String NTPClient::getHours(time_t moment) {
	if ((timeStatus() != timeNotSet) || (moment != 0)) {
		return printDigits(hour(moment));
	}
	else return F("Hours not set");
}
String NTPClient::getHours() {
	return getHours(now());
}

String NTPClient::getDay(time_t moment) {
	if ((timeStatus() != timeNotSet) || (moment != 0)) {
		return printDigits(day(moment));
	}
	else return F("Day not set");
}
String NTPClient::getDay() {
	return getDay(now());
}

String NTPClient::getMonth(time_t moment) {
	if ((timeStatus() != timeNotSet) || (moment != 0)) {
		return printDigits(month(moment));
	}
	else return F("Month not set");
}
String NTPClient::getMonth() {
	return getMonth(now());
}

String NTPClient::getYear(time_t moment) {
	if ((timeStatus() != timeNotSet) || (moment != 0)) {
		return printDigits(year(moment));
	}
	else return F("Year not set");
}
String NTPClient::getYear() {
	return getYear(now());
}
```

**Comment by RudyFiero** [comment]
I just briefly looked at this. While it is nice to have a call for each item I would be concerned about rollover issues. Like the seconds changing from 59 to 0 and then the minute increments. (a bigger concern with higher rollovers) And if the rollover happens between your calls then you end up with the incorrect time. I think it would be better to do one call that populates a structure and then you get to pick out what you need from it. Only one now. Not multiple.

**Comment by Azuzula** [comment]
Aha, good point. I thought its save all data in variable "moment" filled in one NTP call and then I can pick what I need before next call happen.
I understand now, it is better one call and then parse data from string what I get.

**Comment by gmag11** [comment]
I think there is a little misunderstanding  of what this library does.

It does not keep or count time, so its intention is not to get time or date from your sketch. That task is performed by [Time library by Paul Stroffregen](https://github.com/PaulStoffregen/Time). That's where `now()` and other functions you need are coded.

NTPClientLib connects a NTP server two times a day, for instance, to keep time in sync. I coded some functions to get string encoded date for my convenience, but it is not library's core.

You don't need to force NTP sync to get time, time keeping and time synchronization are independent tasks done in different libraries.

I'll keep this issue open for the moment if you like to add some comments.
