### ISSUE TITLE
How to wait until sync is complete?

### ISSUE THREAD

**Issue by DarkShadowNight** [gmag11/NtpClient#35]
Hello,

First of all, thanks for the great library.
But I need some help.

I want when I call getTime the time is accurate from the first time. and not somewhere 1/1/1970.
Is there a way to force and wait for sync?

> 0 00:00:25 01/01/1970
> 1 00:00:26 01/01/1970
> 2 00:00:27 01/01/1970
> Got IP: 192.168.1.2
> Time Sync error: NTP server not reachable
> 3 00:00:00 01/01/1970
> 4 00:00:01 01/01/1970
> 5 00:00:02 01/01/1970
> 6 00:00:03 01/01/1970
> 7 00:00:04 01/01/1970

This piece is crap

> 8 19:04:30 29/05/2017

This should be already in the first call.

Got NTP time: 19:04:30 29/05/2017
9 19:04:31 29/05/2017

I also want to get rid of the syncEvent in the main loop.

Kind regards

**Comment by gmag11** [comment]
You can use `onNTPSyncEvent` to get information about NTP sync status. So you can control what your loop code does.
