### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by rishikeshayre1310** [gmag11/NtpClient#36]
i tried to compile the code NTPClientESP8266 on Arduino IDE 1.8.3
i get the following error 

`NTPClientESP8266:51: error: variable or field 'onSTAGotIP' declared void

 void onSTAGotIP(WiFiEventStationModeGotIP ipInfo) {

                 ^

NTPClientESP8266:51: error: 'WiFiEventStationModeGotIP' was not declared in this scope

NTPClientESP8266:59: error: variable or field 'onSTADisconnected' declared void

 void onSTADisconnected(WiFiEventStationModeDisconnected event_info) {

                        ^

NTPClientESP8266:59: error: 'WiFiEventStationModeDisconnected' was not declared in this scope

NTPClientESP8266:51: error: variable or field 'onSTAGotIP' declared void

 void onSTAGotIP(WiFiEventStationModeGotIP ipInfo) {

                 ^

NTPClientESP8266:51: error: 'WiFiEventStationModeGotIP' was not declared in this scope

NTPClientESP8266:59: error: variable or field 'onSTADisconnected' declared void

 void onSTADisconnected(WiFiEventStationModeDisconnected event_info) {

                        ^

NTPClientESP8266:59: error: 'WiFiEventStationModeDisconnected' was not declared in this scope

C:\Users\AIY5KOR\Documents\Arduino\libraries\NtpClient-master\examples\NTPClientESP8266\NTPClientESP8266.ino: In function 'void setup()':

NTPClientESP8266:85: error: 'WiFiEventHandler' does not name a type

  static WiFiEventHandler e1, e2;

         ^

NTPClientESP8266:105: error: 'e1' was not declared in this scope

  e1 = WiFi.onStationModeGotIP(onSTAGotIP);// As soon WiFi is connected, start NTP Client

  ^

NTPClientESP8266:105: error: 'class ESP8266WiFiClass' has no member named 'onStationModeGotIP'

  e1 = WiFi.onStationModeGotIP(onSTAGotIP);// As soon WiFi is connected, start NTP Client

            ^

NTPClientESP8266:105: error: 'onSTAGotIP' was not declared in this scope

  e1 = WiFi.onStationModeGotIP(onSTAGotIP);// As soon WiFi is connected, start NTP Client

                               ^

NTPClientESP8266:106: error: 'e2' was not declared in this scope

  e2 = WiFi.onStationModeDisconnected(onSTADisconnected);

  ^

NTPClientESP8266:106: error: 'class ESP8266WiFiClass' has no member named 'onStationModeDisconnected'

  e2 = WiFi.onStationModeDisconnected(onSTADisconnected);

            ^

NTPClientESP8266:106: error: 'onSTADisconnected' was not declared in this scope

  e2 = WiFi.onStationModeDisconnected(onSTADisconnected);

                                      ^

exit status 1
variable or field 'onSTAGotIP' declared void

`

**Comment by gmag11** [comment]
This may be due to you are not using latest esp8266 arduino framework. I recommend you to install it directly from git repository

**Comment by gmag11** [comment]
A new staging release has been published a few weeks ago. You can use it to get everything working
