### ISSUE TITLE
Support for Fractional Time Zones?

### ISSUE THREAD

**Issue by 4GLTE** [gmag11/NtpClient#39]
I'm trying to use this library with ESP8266 but facing a hard time synchronizing to fractional time zones. For example, the following are some of the  places which uses fractional time zones 

> Adelaide, South Australia, Australia   GMT +9:30 hours 
> Kabul, Afghanistan                     GMT +4:30 hours 
> Rangoon, Myanmar                       GMT +6:30 hours 
> Kathmandu, Nepal                       GMT +5:45 hours 
> New Delhi, India                       GMT +5:30 hours 
> St. John's, Newfoundland, Canada       GMT -3:30 hours 
> Tehran, Iran                           GMT +3:30 hours 

I tried playing with changing the value 1 in the code below to a fractional value (Ex. 5.5), but to no luck. Am I doing something wrong or unexpected?   
```
NTP.begin("pool.ntp.org", 1, true);
  NTP.setInterval(30, 3600);
```
Also what does "True" and 30, 3600 in the above code achieve?

Please feel free to point me to the documentation if these queries has been answered previously.

**Comment by gmag11** [comment]
Hi,

Yes, it's true. I noticed this when creating this code. Internal SNTP esp8266 SDK functions do not support fractional time offset.

I'm planning to implement my own SNTP parser to avoid some SDK pitfails and integrating ESP8266 and Arduino code in same file. But there is no time schedule yet :(

Regards

**Comment by 4GLTE** [comment]
Thanks for your clarification and response.
