### ISSUE TITLE
No Sync at first time

### ISSUE THREAD

**Issue by Fatmax1982** [gmag11/NtpClient#4]
Tried the ESP8266 example but i don't get sync at first time after power on the ESP8266.
I changed the url to "at.pool.ntp.org" for testing but same result.
I only get "-- NTP error :-( ".

![image](https://cloud.githubusercontent.com/assets/21036776/17706106/023ca220-63db-11e6-8faf-33950715217c.png)

When the sync is done after customized interval (tried with 60 seconds), time is synced and shown on the serial monitor.

What's wrong?

**Comment by gmag11** [comment]
Check what version of esp8266 Arduino framework you are using. With latest commit it works. How have you installed, got or Arduino IDE?

**Comment by Fatmax1982** [comment]
Updated Arduino IDE from 1.6.7 to 1.6.10, flashed again to ESP8266 and still have the same problem.

**Comment by Fatmax1982** [comment]
Is there any other solution?

**Comment by gmag11** [comment]
I do boot mean arduino IDE. I mean esp8266 framework on [github.com/esp8266/arduino](https://github.com/esp8266/Arduino) follow instructions there to use latest code directly from github. Read "Using git version" section in readme.md.

I've updated my code recently. You can test it and check if there is a different behaviour.

**Comment by gmag11** [comment]
I've added more checkings. You will still get an error (WiFi not connected) during first moments if you do not control if WiFi is connected in your Scketch. But NTP packet is not sent if WiFi is not connected. To use latest commits you need to use my TimeLib fork. See https://github.com/gmag11/NtpClient/issues/5.

If you do not like that behabiour, you can check WiFi is connected before throwing `NTP.begin();` so NTP will not give connection errors.

**Comment by gmag11** [comment]
I've updated ESP8266 example to trigger `NTP.begin()` as soon as WiFi gets a valid IP address. Please test it and close the issue it it is ok.

**Comment by Fatmax1982** [comment]
Tested it and now it works.
Thanks!
