### ISSUE TITLE
mem leak(s)

### ISSUE THREAD

**Issue by devyte** [gmag11/NtpClient#40]
In file ESPNTPClient.cpp, method NTPClient::setNtpServerName(...)

`	char * buffer = (char *)malloc((ntpServerName.length()+1) * sizeof(char));
`

A buffer gets malloc'd every time ::setNtpServerName() gets called, which gets called from ::begin(). There is no corresponding free() call to this malloc, and I doubt that the SDK internals do mem management for this buffer. Of course, I could be wrong, I haven't actually tested whether calling begin() again and again reduces mem.

If this is in fact a mem leak, I suspect that a fix would be to call sntp_getservername(idx), check for the returned ptr != nullptr. If so, free it, then proceed as now with setting it again.
If that doesn't work, then a local array of size 3 would be needed to store the malloc'd pointers, and manage them before calling sntp_setservername().

Additionally, there is no check if the returned ptr from malloc is nullptr (malloc failed).

Finally, if the idx arg passed to the method is outside the range 0-2, the malloc is done, but the pointer is never assigned to anything due to the if statement, so the mem leaks when the method returns.

**Comment by devyte** [comment]
Something along these lines is what I had in mind (untested!):
``` Arduino
bool NTPClient::setNtpServerName(String ntpServerName, int idx)
{
	if ((idx >= 0) && (idx <= 2)) {
		char * buffer = (char *)malloc((ntpServerName.length()+1) * sizeof(char));
		if(buffer == nullptr)
			return false;
		sntp_stop();
		char * old = sntp_getservername(idx);
		free(old); //if old is nullptr, nothing happens, per standard
		ntpServerName.toCharArray(buffer, ntpServerName.length()+1);
		sntp_setservername(idx, buffer);
		DEBUGLOG("NTP server %d set to: %s \r\n", idx, buffer);
		sntp_init();
		return true;
	}
	return false;
}

```

**Comment by gmag11** [comment]
You're right, thank you.

Have you tested that this code works?
``` Arduino
char * old = sntp_getservername(idx);
free(old);
```

If so, please make a pull request. If you can't (for any reason) please let me know.

Regards

**Comment by trentbrown13** [comment]
I am using a program(s) that use ntpClientLib with modem sleep. When using ntpClientLib, there is a heap loss on every re-connect when the modem "wakes" up and ntp restarts until I finally run out of memory and it resets (usually around 24+ hours with a 1 minute sleep).
 If I comment out (or #ifdef out) all ntp references and just let the modem disconnect/reconnect the heap stays stable.

I'll be glad to try any proposed patch if you need a tester

thanks
-trent

**Comment by gmag11** [comment]
Most probably, as there is a reconnection of WiFi network new object instances are created without cleaning old ones out.
I'm rewritting this lib completely to add new features. Currently it uses Espressif internal SDK sntp funtions, so I'm restricted to its features. Development is slower than I would like so there is no ETA yet.
As a workaround you can use TimeLib examples together with sntp from SDK. It should work.

**Comment by trentbrown13** [comment]
Thank you, I'll be glad to try out your new lib when you are ready for some testing.

As a workaround (still using your library)  I start ntp just once in  setup and let it run through each connect/disconnect by not restarting it with onSTAGotIP event.  My modem sleeps are fairly short (< 1 minute) so it apparently  works fine for this application.

**Comment by devyte** [comment]
@gmag11 I've been testing the proposed code for a while, and it seems to work well. Now that I finished the cleanup of the Arduino issues I'm moving on to PRs, so I'll be making one of this soon.

**Comment by trentbrown13** [comment]
This is probably a stupid question/observation, but all my esp's running NtpClient started reporting current time as current time minus 1 hour this morning (11-01-2017). At first I thought all of them had crashed an hour ago (very weird) but then saw the stats were updating. It is close to daylight savings time change (this coming Sunday, 11-05-2017) and I am on PST time .

Setup is like this
Global:
int8_t timeZone = -8

in setup:
 NTP.begin("pool.ntp.org", timeZone, true);
  NTP.setInterval(63);

and publishing is like this
void publishNTP(void)
{
    String currDate = NTP.getTimeDateString();
    String upTime = NTP.getUptimeString();
    String bootDate = (NTP.getTimeDateString(NTP.getFirstSync()).c_str());

    client.publish("TbOfficeClient/upTime", upTime.c_str());
    client.publish("TbOfficeClient/currTime", currDate.c_str());
    client.publish("TbOfficeClient/bootTime", bootDate.c_str());
}

**Comment by gmag11** [comment]
Please test new beta version on https://github.com/gmag11/NtpClient/tree/pre2.5.0. I've rewritten all sync stuff and added ESP32 as supported platform.
