### ISSUE TITLE
request->send_P(200, "text/html", Page_Restart) not sending 

### ISSUE THREAD

**Issue by ddamron** [gmag11/NtpClient#41]
This is in the demo code a couple of times, but doesn't seem to work.

If I'm not mistaken, it's supposed to send a message, then delay and reload..

my PROGMEM is: 
const char Page_Restart[] PROGMEM = R"=====(
<meta http-equiv="refresh" content="25; URL=/general.html">
Please Wait....Configuring and Restarting.
)=====";

yet I never get a page that once executed.  As a matter of fact, seem to be still waiting for a response, then times out..

Can someone confirm these findings?  Anyone have a solution?

**Comment by gmag11** [comment]
I guess this belongs to FSBrowserNG repository. It is a known issue. I have not much time to solve it, sorry. I close this issue as it is not related to NTPClient
