### ISSUE TITLE
For esp8266 this library simply overhead. It doesn't do anything usefull

### ISSUE THREAD

**Issue by tantra35** [gmag11/NtpClient#42]
This library actualy doesn't make any ntp communications, and simply call espressif SDK with huge overhead. For example function `sntp_get_current_timestamp();` just simple return constant inside SDK, that was goted by SDK after some commucations with NTP servers(look at src https://github.com/esp8266/Arduino/blob/master/tools/sdk/lwip/src/core/sntp.c#L622). So if you periodicaly will call sntp_get_current_timestamp inside `loop` it will be the same what do this lib

**Comment by gmag11** [comment]
You are not forced to use if you don't like it. My intention is make NTP sync as easiest as possible. If you think you can do it better, what I'm sure of, simply do it. I'm sorry if you have lost some of your minutes analyzing this code. :)
