### ISSUE TITLE
Support for ESP32

### ISSUE THREAD

**Issue by species5618** [gmag11/NtpClient#43]
I have not dug too deep, but the code seel to explicility expect a ESP8266 or arduino AVR
is there aplan for a ESP32 compatable version, 

I am currently looking at which depencises for FSBrowserNG required tweaks for ESP32

**Comment by bill-orange** [comment]
I could use a ESP32 version for my Wundergound applications.

**Comment by gmag11** [comment]
Hi, I'm working to make this project use more standard code. This has several advantages:
- Compatible with more platforms
- Space for improvements. Current version is using internal ESP8266 sdk. It has some limitations. Implementing this in standard Arduino code makes me able to get better features (like millisecond precission ;-)
You can test https://github.com/gmag11/NtpClient/tree/platforms_integration . This is work in progress, so it may have some bugs or not work at all. Test it.

**Comment by gmag11** [comment]
Hi, esp32 support is just finished and ready for testing. Have a look on https://github.com/gmag11/NtpClient/tree/pre2.5.0
