### ISSUE TITLE
getLastNTPSync always returns zero until call to another function

### ISSUE THREAD

**Issue by riban-bw** [gmag11/NtpClient#45]
Within setup() call NTP.begin().
Within loop() call NTP.getLastNTPSync() returns zero.

Calling NTP.getTimeDateString() (for example) triggers getLastNTPSync to return a non-zero value.

**Comment by gmag11** [comment]
I've been working on new version. You can use it for testing. It is on https://github.com/gmag11/NtpClient/tree/pre2.5.0
