### ISSUE TITLE
How to Set Timezone which has minutes offset too?

### ISSUE THREAD

**Issue by ayushsharma82** [gmag11/NtpClient#46]
Hello,
I Live in India so it's 5 Hours and 30 Minutes ahead of UTC.
Please Tell me how to add minutes offset in Timezone at begin() ?

I am trying 5 , But yeah it is 30 minutes behind. 
ntp server - in.pool.ntp.org

**Comment by gmag11** [comment]
Hi, you can test https://github.com/gmag11/NtpClient/tree/pre2.5.0. There is a method to set minutes offset
