### ISSUE TITLE
Compilation error for ESP8266 

### ISSUE THREAD

**Issue by reaper7** [gmag11/NtpClient#5]
I can't compile NTPClientESP8266 example (Arduino 1.6.11 with latest esp8266 core from github :

```
C:\PROGRAMY\arduino_projekty\libraries\NtpClient\src\ESPNTPClient.cpp: In member function 'bool NTPClient::begin(String, int, bool)':

C:\PROGRAMY\arduino_projekty\libraries\NtpClient\src\ESPNTPClient.cpp:129:53: error: cannot convert 'std::_Bind_helper<false, long int (NTPClient::*)(), NTPClient* const>::type {aka std::_Bind<std::_Mem_fn<long int (NTPClient::*)()>(NTPClient*)>}' to 'getExternalTime {aka long int (*)()}' for argument '1' to 'void setSyncProvider(getExternalTime)'

  setSyncProvider(std::bind(&NTPClient::getTime,this));

                                                     ^

exit status 1
Błąd kompilacji dla płytki WeMos D1 R2 & mini.
```

but earlier versions, before 17 aug (maybe before "Migrate ESP version to std::function()") works for me OK

**Comment by vchrisb** [comment]
I have the same issue.

**Comment by gmag11** [comment]
Ah ok, I made a change on TimeLib library to accept `std::function`. I've proposed a pull to his author but it has not been accepted yet. You need to use my [TimeLib fork](https://github.com/gmag11/Time) if you want to run versions after 17th august. Sorry for the annoyance.

**Comment by reaper7** [comment]
@gmag11 - tnx for info, with Your fork of TimeLib everything works OK :+1:

**Comment by vchrisb** [comment]
thx @gmag11 !
IMHO you should not release a new version before your pull request is accepted.
Looking at the history of the time repo it does not look like it will be merged soon.

**Comment by gmag11** [comment]
I'm thinking about rolling back the use of std::function on TimeLib. There are quite a few open pull requests on its repository. So most probably my pull will not be included on original lib
I will stitch to original TimeLib features so you don't need to use my fork.

**Comment by gmag11** [comment]
Meanwhile you can use my TimeLib fork or stay with [commit before modification](https://github.com/gmag11/NtpClient/commit/edb6e511684c510716200d949610afc80bfedbba). My roll back will not affect library interface, so it will be transparent for your code.

**Comment by gmag11** [comment]
Last commit should work with original TimeLib.h. Please test it.

**Comment by reaper7** [comment]
Yes, it's true, tested :+1:
