### ISSUE TITLE
does not work with newest arduino software

### ISSUE THREAD

**Issue by matmay** [gmag11/NtpClient#51]
I updated today with the arduino boards manager and afterwards time sync didn't work anymore.

it works with "Arduino AVR Boards by Arduino version 1.6.15" and "esp866 by ESP8266 Community version 2.3.0" and does not work with 1.6.20 and 2.4.0, respectively.

I'm using

```
#include<ESP8266WiFi.h>
#include <ESP8266WebServer.h>
#include <TimeLib.h>
#include <NtpClientLib.h>
#include "FS.h"
```

on an ESP-8266 12E board

**Comment by gmag11** [comment]
I'm testing with latest ESP8266 Arduino core. Could you copy some debug output here?
Do you have any problem during compilation?

**Comment by Tirantet** [comment]
I report the same issue, my project crash with new version.
If I downgrade the library to 2.0.5 all works as expected.

I use ESP12F

**Comment by matmay** [comment]
It just does not work, it compiles without error. I have the sketch send me
debug over serial if there is a time sync or an error and neither of those
is sent to me.

Am 21.01.2018 22:45 schrieb "Germán Martín" <notifications@github.com>:

**Comment by Tirantet** [comment]
My project compiles perfect, but when run and the "NTP loop" routine executes, the module is halted with a exception.

While the module is not connected to Internet works, but if the module get connection in this moment (NTP loop detect connection)... crash

**Comment by bill-orange** [comment]
Even running with board manager 2.30, I had to add the following line to loop to get it to work  No compile problems, however.  This was not necessary in ver. 2.0 of the library

`while (actualTime == 0) actualTime = (NTP.getTime());`

**Comment by gmag11** [comment]
I'm not able to reproduce such behaviour. Please, enable DEBUG log and copy the result and your code here. Thanx.

**Comment by bill-orange** [comment]
It may be a while before I can run with debug.  Here is the code.  Sorry about the size but if I give you fragments, I might leave out something important.

**Comment by gmag11** [comment]
@bill-orange , I've deleted the link in your message. It seems you made a mistake selecting what to share.

**Comment by bill-orange** [comment]
@gmag11  Sorry about that!

https://1drv.ms/u/s!AmXKqAwyCrbxh-RiHb21AnxtNBU7vA

Here's what it does.

http://orangecaweather.duckdns.org:8021/

The idea is to get actual temperature from a sensor, wunderground actual temperature, wunderground future temperatures and make a very accurate local short term forecast. I use NTPclientLib to get a unix time mark each data point.  The referenced code runs fine with ver 2.05 but with no changes ver 2.5 gives zeros after 12 - 24 hours.  Once it starts delivering zeros, it never recovers.

**Edit ** It also appears that when testing with the ver. esp8266 2.3 core that FTP is nearly blocked using the ver. 2.5 library.  Odd.

**Comment by gmag11** [comment]
You are doing many `NTP.getTime()` calls in your code. Normally you should not do that. NTPClientLib aims to synchronize time from a NTP server. All time keeping is done in TimeLib library that NTPClientLib uses.

To get Unix time you should call `now()` instead.
