### ISSUE TITLE
Wrong time after updating to 2.5.0

### ISSUE THREAD

**Issue by snoutmate** [gmag11/NtpClient#52]
Hello, after updating NTPClient from 2.0.5 to 2.5.0, i'm getting wrong time - it appears the NTP.begin() runs the NTP sync twice, with wrong result.

Code:
setup() 
{
  NTP.begin("ntp.nic.cz", 1, true);
 }

Debug output with -DDEBUG_NTPCLIENT:

NTP server set to ntp.nic.cz
NTP time zone set to: 1
--Set daylight saving ON
Starting UDP
-- Receive NTP Response
Winter Time
Sync frequency set low
Successful NTP sync at 17:51:30 18/01/2018Short sync interval set to 15
Long sync interval set to 1800
Time sync started
Starting UDP
-- Receive NTP Response
Winter Time
Sync frequency set low
Successful NTP sync at 07:28:16 07/02/2036

**Comment by gmag11** [comment]
What platform are you using?

**Comment by snoutmate** [comment]
@gmag11 esp8266 with Arduino core 2.4.0

**Comment by gmag11** [comment]
It has been working on my side with my local ntp server (es.pool.ntp.org). I will try yours (ntp.nic.cz)

**Comment by gmag11** [comment]
I've got same result. Please if stil failing share your code with me so I can have a look.
```
NTP server set to ntp.nic.cz
NTP time zone set to: 1
--Set daylight saving ON
Time sync started
Starting UDP
NTP Server IP: 217.31.202.100
-- Receive NTP Response
Winter Time
Sync frequency set low
Successful NTP sync at 15:39:23 08/03/2018
Sync interval set to 63
Got NTP time: 15:39:23 08/03/2018
1 15:39:26 08/03/2018 Winter Time. WiFi is connected. Uptime:    0 days 00:00:10 since 15:39:23 08/03/2018
2 15:39:31 08/03/2018 Winter Time. WiFi is connected. Uptime:    0 days 00:00:15 since 15:39:23 08/03/2018
3 15:39:36 08/03/2018 Winter Time. WiFi is connected. Uptime:    0 days 00:00:20 since 15:39:23 08/03/2018
4 15:39:41 08/03/2018 Winter Time. WiFi is connected. Uptime:    0 days 00:00:25 since 15:39:23 08/03/2018
5 15:39:46 08/03/2018 Winter Time. WiFi is connected. Uptime:    0 days 00:00:30 since 15:39:23 08/03/2018
6 15:39:51 08/03/2018 Winter Time. WiFi is connected. Uptime:    0 days 00:00:35 since 15:39:23 08/03/2018
```
