### ISSUE TITLE
setInterval (int shortInterval, int longInterval) not respected

### ISSUE THREAD

**Issue by MarcFinns** [gmag11/NtpClient#53]
The newest version seems to have an issue in not honouring the intervals defined with setInterval (int shortInterval, int longInterval).
Specifically, in case the first synchronisation fails (e.g. server not reachable) one would expect the lib to retry after a shortInterval, but in fact it waits the full longInterval.
Any chances you could have a look? thanks

**Comment by gmag11** [comment]
Yes, I'll have a look ASAP

**Comment by MarcFinns** [comment]
Thanks. I also have the impression that onNTPSyncEvent is called twice (I see two logs)

**Comment by MarcFinns** [comment]
Hi, I see a commit related to this issue but no new release. 
Is it to be tested? Can I help? Thanks!

**Comment by gmag11** [comment]
Yes, please try [develop](https://github.com/gmag11/NtpClient/tree/develop) branch

**Comment by MarcFinns** [comment]
Hi, how stable is the development branch? Shall i wait a merge or use it?

**Comment by gmag11** [comment]
It should be fairly stable. Use and notify any bug, please
