### ISSUE TITLE
NTP_TIMEOUT 1500 to short

### ISSUE THREAD

**Issue by AlbertWeterings** [gmag11/NtpClient#56]
It seems NTP_TIMEOUT is to short (no response from server) 
If I use my local NTP server most of the times it works when using a remote NTP server (I tested with 15) the lowest possible value is 2000 ms.

Maybe something to look into if more people have this issue.

**Comment by gmag11** [comment]
I'm planning to migrate ESP8266 and ESP32 code to use async UDP library. Meanwhile, having 2 seconds time is too long to have a blocking function. Anyway if it works in your case, you can change it in your local library copy. Thanks

**Comment by AlbertWeterings** [comment]
Maybe it is a option to make it a configurable variable.

**Comment by gmag11** [comment]
It's done, check develop branch
