### ISSUE TITLE
How to enable printing debug information to Serial port

### ISSUE THREAD

**Issue by vhatsura** [gmag11/NtpClient#57]
First of all, sorry for this stupid question, but I cannot enable printing debug info into Serial port.

I found following code in sources:
https://github.com/gmag11/NtpClient/blob/213d400396d5704952622c4d8cd3709d2e7075ef/src/NTPClientLib.cpp#L34-L40

Then in my sketch I use `#define DEBUG_NTPCLIENT 1` but cannot see any debug info in Serial monitor

**Comment by gmag11** [comment]
You have to uncomment this
https://github.com/gmag11/NtpClient/blob/213d400396d5704952622c4d8cd3709d2e7075ef/src/NtpClientLib.h#L41

**Comment by vhatsura** [comment]
Got it. Thanks
