### ISSUE TITLE
Latest github version with 1.6.8

### ISSUE THREAD

**Issue by kiralikbeyin** [gmag11/NtpClient#6]
/Users/EvAkilli/Documents/Arduino/libraries/NtpClientLib/src/NtpClientLib.h:60:2: error: #error "Incorrect platform. Only ARDUINO and ESP8266 MCUs are valid."
 #error "Incorrect platform. Only ARDUINO and ESP8266 MCUs are valid."
  ^

**Comment by gmag11** [comment]
To be compatible with both Arduino and ESP8266 NTPClientLib.h uses `ARDUINO_ARCH_ESP8266` and `ARDUINO_ARCH_AVR` defines.

They are defined by IDE enviroment depending on which board is selected. Please check that your IDE defines `ARDUINO_ARCH_ESP8266` and you have selected the right board.
