### ISSUE TITLE
Compile error of example

### ISSUE THREAD

**Issue by Tommy-LSA** [gmag11/NtpClient#72]
Arduino IDE 1.8.5, Windows 8.1 

#include <TimeLib.h>

                     ^

compilation terminated.

exit status 1
Fehler beim Kompilieren für das Board Generic ESP8266 Module.

**Comment by gmag11** [comment]
Please update esp8266 Arduino Core. Check it on Boards manager.

**Comment by Tommy-LSA** [comment]
The package is fresh installed a few days ago. The URI is http://arduino.esp8266.com/stable/package_esp8266com_index.json 
The installed ESP8266 version is 2.4.2, no updates available.

**Comment by gmag11** [comment]
Do you have time library installed?

**Comment by Tommy-LSA** [comment]
This was the issue. Thanks for the hint
