### ISSUE TITLE
Daylight Saving Time

### ISSUE THREAD

**Issue by yknivag** [gmag11/NtpClient#73]
The method of calculating daylight saving time (DST) in this library is flawed for several reasons:

1. Not every country has DST.
2. Not every timezone changes to DST on the same day.
3. The date of change in many countries varies from year to year.
4. The formula for calculating the start and end dates varies from country to country and can be quite complex.  For example in the UK DST starts at 02:00 on the last Sunday of March where that Sunday is no later than the 30th of March. (If Sunday is the 31st then the change happens the week before!)  The same rule applies for the end in October.
5. Not every timezone adds 1hr for DST.  Some add 30mins and some 90.

There is no mention in the documentation for this library that this functionality is essentially broken.

Maybe rather than trying to create a piece of code to calculate this it would be better to use a webservice such as those listed below to query the tzdata database which would give accurate results for everyone regardless of their location?

A couple of options for getting true DST rules are:
[https://timezonedb.com/references/get-time-zone](https://timezonedb.com/references/get-time-zone)
[https://developers.google.com/maps/documentation/timezone/intro](https://developers.google.com/maps/documentation/timezone/intro)

**Comment by Diramu** [comment]
I have a fork version that supports all timezone.  I'll be creating a pull request soon.
It does not enquire to find timezone parameter but you supply all posix parameters.

**Comment by BCChad** [comment]
This is a relevant issue.  Here in US - it turned 1 November today and the routine is declaring end of DST, but actually  DST continues until 4 November.

**Comment by gmag11** [comment]
As NTP protocol works with UTC time only I do not plan to improve TZ and daylight saving calculation. I include those functions for convenience only but they are not part of the core code.
