### ISSUE TITLE
TimeZone integration

### ISSUE THREAD

**Issue by Bolukan** [gmag11/NtpClient#78]
Great library, also because ESPAsync (and dns_gethostbyname) will be implemented in v3. 

Many users appreciate good TimeZone support, which I define as supporting DST and keeping UTC as systemtime ([or at least have it available](https://github.com/gmag11/NtpClient/issues/13#issuecomment-249387749)). I also fully understand your [opinion](https://github.com/gmag11/NtpClient/issues/73#issuecomment-451548514) to not include advanced timezone support into the library. I came to the idea to include an example that uses the https://github.com/JChristensen/Timezone library. Together with TimeLib it would cover any use case. Would you support this idea?

**Comment by gmag11** [comment]
Sure, you may use them together if they fit your need.
Besides, I've found this library that lets you adjust DST period instead calculating it. It should be more memory efficient than keeping a table with all possible DST country specific settings or asking Google API.
Check https://github.com/neptune2/simpleDSTadjust

**Comment by Bolukan** [comment]
That library is ok for some applications, but it only supports DST if your clock is set to the wintertime of the timezone. It does not support both UTC and a TimeZone.
