### ISSUE TITLE
ESP8266 compile error

### ISSUE THREAD

**Issue by zivyuan** [gmag11/NtpClient#8]
here is the message:

> .pioenvs/esp07/NtpClientLib_ID727/ESPNTPClient.cpp: In member function 'bool NTPClient::begin(String, int, bool)':
> 
> .pioenvs/esp07/NtpClientLib_ID727/ESPNTPClient.cpp:129:53: error: cannot convert 'std::_Bind_helper<false, long int (NTPClient::*)(), NTPClient* const>::type {aka std::_Bind<std::_Mem
> _fn<long int (NTPClient::*)()>(NTPClient_)>}' to 'getExternalTime {aka long int (_)()}' for argument '1' to 'void setSyncProvider(getExternalTime)'
> setSyncProvider(std::bind(&NTPClient::getTime,this));
> ^

**Comment by gmag11** [comment]
I will check tomorrow. Thank you. What release / branch / commit are you trying to compile?

**Comment by zivyuan** [comment]
I'm using the PlatformIO library manager to manage my libs, it's should be the newest. NTP lib version marked as 2.0.2

My system env.:
Mac OS X EI Capitan, Xcode 7.3.1  installed.

**Comment by gmag11** [comment]
I've just released 2.0.3. It should fix that error. It was my fault. It can take a couple of days to propagate to Arduino and PIO library managers. You can use git if you need the update now.

**Comment by zivyuan** [comment]
It's work! Very THX!
