### ISSUE TITLE
SIM800 GSM

### ISSUE THREAD

**Issue by oleslavs** [gmag11/NtpClient#81]
Hello! Please help!
Im using SIM800 GSM via TinyGSMclient library, but no examples of code how use NTPClient in my case. Im search a lot but not found how tu use udp: Reference to an UDP object with TinyGSMclient.h
Is exist many examples of ethernet or wi-fi but none of GSM.

**Comment by gmag11** [comment]
TinyGSM library does not support UDP. Besides, even if it would, it should use same interface as Arduino UDP implementation. I guess you will have to use plain AT commands.

**Comment by oleslavs** [comment]
Thank you! I`m using <b>getGSMDateTime</b> function instead AT-commands but it not work always fine.  Somtimes it returns  zero time.
