### ISSUE TITLE
WiFi locked if I setup a web server with ESP8266WebServer using NtpClient 

### ISSUE THREAD

**Issue by bubibubi** [gmag11/NtpClient#82]
After the first sync all the wifi locks (it also does not respond to ping).
It continue to sync with NTP.

The web server is set up as the library example.

**Comment by bubibubi** [comment]
Looking around I'm starting to think that ntp update is called when i'm doing something different with wifi. Is there a way to disable automatic NTP update so I can call when I'm sure that the WiFi is not used?

**Comment by bubibubi** [comment]
The issue is definitely related to concurrency. I removed the code that syncs the device with the NTP server and I'm calling getTime manually when I'm not using Web Server. Everything is working.

**Comment by gmag11** [comment]
NTP is synchronizer periodically every time you configure. You can do manual synchronization using setTime(NTP.getTime()) in any moment. You can try to configure a very big period. Do you have any example code?

**Comment by bubibubi** [comment]
I'm using manual synchronization (as your suggestion) so it works fine.
If I use wifi to do other things (for example I set up a web server on arduino and I use it from pc) and the the NTP automatic synchronization runs while I'm accessing the web server, the wifi stop works.
Configuring big periods reduces only the probability but is not a solution.
I threw away the old code but you can probably reproduce the error running a web server on arduino that returns a very simple page. If you start the sketch and press refresh often (while NTP automatic synchronization is enabled), after a while everything should stop work.

**Comment by gmag11** [comment]
Please test latest version 3.0.0-beta
