### ISSUE TITLE
Example should list easy to use time functions (hour() , minute() , second() etc)

### ISSUE THREAD

**Issue by ajaybnl** [gmag11/NtpClient#83]
Serial.print ("TIME: ");
Serial.print (hour());
Serial.print(":");
Serial.print (minute());
Serial.print(":");
Serial.println (second());

Serial.println ();

Serial.print ("Date: ");
Serial.print (day());
Serial.print("/");
Serial.print (month());
Serial.print("/");
Serial.println (year());

**Comment by gmag11** [comment]
These functions do not belong to this library but to [TimeLib](https://github.com/PaulStoffregen/Time). You can read about their use there.
