### ISSUE TITLE
ESP8266 Example Contantly returns disconnected error 201 when WiFi has acheived connection?

### ISSUE THREAD

**Issue by dachshund-digital** [gmag11/NtpClient#85]
If I disable the handler...

27 00:02:40 01/01/1970 Winter Time. WiFi is connected. Uptime:    0 days 00:02:40 since 00:00:00 01/01/1970
28 00:02:45 01/01/1970 Winter Time. WiFi is connected. Uptime:    0 days 00:02:45 since 00:00:00 01/01/1970
29 00:02:50 01/01/1970 Winter Time. WiFi is connected. Uptime:    0 days 00:02:50 since 00:00:00 01/01/1970
30 00:02:55 01/01/1970 Winter Time. WiFi is connected. Uptime:    0 days 00:02:55 since 00:00:00 01/01/1970
31 00:03:01 01/01/1970 Winter Time. WiFi is connected. Uptime:    0 days 00:03:01 since 00:00:00 01/01/1970
32 00:03:06 01/01/1970 Winter Time. WiFi is connected. Uptime:    0 days 00:03:06 since 00:00:00 01/01/1970
33 00:03:11 01/01/1970 Winter Time. WiFi is connected. Uptime:    0 days 00:03:11 since 00:00:00 01/01/1970

If I enable the handler...

Added the following code right after WiFi.begin() to test issue...
    while (WiFi.status() != WL_CONNECTED) {

      Serial.print(".");
      delay(1000);
    }
    Serial.println();
    Serial.print(WiFi.localIP());

Definitely getting an IP from AP, if I enable a web server (additional code of course) the server responds as expected.  So entirely mystified why WiFi disconnect handler is repeatably fires.  More over the GotIP and Connected handlers fail to fire so wifiFirstConnected is never set to true of course.

So added the following to test deeper, just after WiFi.localIP() display...

if (WiFi.isConnected()) {
  wifiFirstConnected=true;
}

This is a cheat of course to fake that the Connected and GotIP handlers fired, which they did not.  No matter what I try, I can't get these handlers to fire.  Tried rebuilding the sketch, tried different ESP8266 devices.  Validated that my AP is working as expected, using other methods.  Feels like a bug, unless further insight?

**Comment by gmag11** [comment]
This is strange and seems to be related with your setup. I recommend you to use latest ESP8266 core 2.5.2. I close the issue. Feel free to reopen it if you like
