### ISSUE TITLE
Cannot find "NTPClientLib.h" due to capitalization error

### ISSUE THREAD

**Issue by sgorpi** [gmag11/NtpClient#9]
On capitalization-sensitive filesystems (as in, linux), the lib won't compile, since the cpp files try to: #include "NTPClientLib.h", while the file is named NtpClientLib.h
Can be fixed using the correct capitalization: #include "NtpClientLib.h"

Thx for the good library!

**Comment by gmag11** [comment]
Thank you for reporting. I will fix it as soon as i can.

**Comment by gmag11** [comment]
Fixed on [latest commit](https://github.com/gmag11/NtpClient/commit/117f4a71af041f00c081a08d219de635f674dac5)
