### ISSUE TITLE
Odd change in time April 1, 2019

### ISSUE THREAD

**Issue by bill-orange** [gmag11/NtpClient#90]
I swear that this is not an April Fool's joke.  I am in Pacific Time, -7 from GMT due to DST.  Last night my many sketches running weather applications crashed due to a time error.  Suddenly,
NTP.begin ("pool.ntp.org", TIMEZONE, true); with TIMEZONE = -7 is reading one hour too late (ie. 8:53 AM when it is 7:53 AM).

All was well yesterday. What could have happened.

P.S. in NTP.begin what does the `true` do?  Could DST management be off?

Bill

**Comment by gmag11** [comment]
Hi @bill-orange . `True` means DST. Somebody told me that algorithm used to calculate DST period is only valid for Europe. Please check #78 and #73, we talk about that there. You may disable internal DST calculation changing `true` with `false` on `begin()` call. #78 recommends using https://github.com/JChristensen/Timezone for timezone calculation

**Comment by bill-orange** [comment]
Thanks. I am sure that was it.
