### ISSUE TITLE
library.json contains a typo

### ISSUE THREAD

**Issue by uherting** [gmag11/NtpClient#95]
library.json has a typo in the requirement section. The line of the lib called "TIME reads "version": "^5.10" but there is no version 5.1 (just 1.5) and I am pretty sure the '^' is not to be intended either.

**Comment by Londoneye02** [comment]
Same error here. 

Trying to build with PlatformIO returns: LibraryManager: Installing id=44 @ ^5.10
Error: Could not find a version that satisfies the requirement '^5.10' for your system 'windows_amd64'

Changin to   "version": "1.5" builds OK.

**Comment by gmag11** [comment]
Thanks, this has been solved on a pull request.
